const catalyst = require("zcatalyst-sdk-node");

async function handler(req, res) {
  try {
    const { key } = req.query || {};
    const app = catalyst.initialize(req);

    if (key) {
      const stratus = app.stratus();
      const file = await stratus.getFile(key);
      res.setHeader("Content-Type", "application/pdf");
      res.setHeader("Content-Disposition", `attachment; filename="${key.split("/").pop()}"`);
      return res.status(200).send(file.file_content);
    }

    const { id } = req.path_params;
    const query = app.datastore().getTable("CaseMaster").getQuery();
    const rows = await query.execute(`
      SELECT cm.*, u.UnitName, d.DistrictName
      FROM CaseMaster cm
      LEFT JOIN Unit u ON cm.UnitID = u.UnitID
      LEFT JOIN District d ON u.DistrictID = d.DistrictID
      WHERE cm.CaseMasterID = ?
    `, { params: [parseInt(id)] });

    if (!rows || rows.length === 0) {
      return res.status(404).json({ status: "error", error: { code: "NOT_FOUND", message: "Case not found" } });
    }

    const c = rows[0];
    const html = `
      <!DOCTYPE html><html><head><style>
        body { font-family: Arial; padding: 30px; color: #1e293b; }
        h1 { color: #1e3a5f; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; }
        .field { margin: 6px 0; }
        .label { font-weight: 600; color: #64748b; width: 140px; display: inline-block; }
      </style></head><body>
      <h1>Case Report — ${c.CrimeNo || "N/A"}</h1>
      <div class="field"><span class="label">Case No:</span> ${c.CaseNo || "—"}</div>
      <div class="field"><span class="label">District:</span> ${c.DistrictName || "—"}</div>
      <div class="field"><span class="label">Station:</span> ${c.UnitName || "—"}</div>
      <div class="field"><span class="label">Registered:</span> ${c.CrimeRegisteredDate ? new Date(c.CrimeRegisteredDate).toLocaleDateString("en-IN") : "—"}</div>
      <div class="field"><span class="label">Brief Facts:</span><br/>${c.BriefFacts || "—"}</div>
      <hr style="margin-top:20px;color:#e2e8f0;"/>
      <p style="font-size:11px;color:#94a3b8;">Generated by KSP Crime Intelligence Platform</p>
      </body></html>
    `;

    const smartbrowz = app.smartbrowz();
    const pdf = await smartbrowz.generatePdf({ html_content: html, page_size: "A4" });

    const stratus = app.stratus();
    const fileKey = `reports/case-${id}-${Date.now()}.pdf`;
    const fileResp = await stratus.saveAsFile({
      file_name: fileKey,
      file_content: pdf.pdf_content,
      content_type: "application/pdf",
    });

    res.status(200).json({
      status: "success",
      data: {
        reportId: fileKey,
        downloadUrl: fileResp.download_url || `/api/reports/download?key=${fileKey}`,
      },
    });
  } catch (err) {
    res.status(500).json({
      status: "error",
      error: { code: "PDF_GEN_FAILED", message: err.message },
    });
  }
}

module.exports = handler;
